import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Navbar from "./Navbar";
import Landing from "./Landing";
import About from "./About";
import Team from "./Team";
import Contact from "./Contact";
import Services from "./Services";
import Footer from "./Footer";
import TopButton from "./TopButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <TopButton />
        <div id="home"></div>
        <Landing />
        <div id="about"></div>
        <About />
        <div id="team"></div>
        <Team />
        <div id="services"></div>
        <Services />
        <div id="contact"></div>
        <Contact />
        <Footer />
      </main>
    </>
  );
}
